[package]
name = "t"
version = "0.1.0"
edition = "2021"

[dependencies]

axum = "0.8.1"
chrono = "0.4.39"
hyper = "1.5.2"
maud = "0.26.0"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

