[build]
target = "index.template.html"
dist = "dist"
no_default_favicon = true

[watch]
watch = ["src", "index.html", "style.css", ".nojekyll"]

[serve]
address = "127.0.0.1"
port = 8080
open = false
